
version: '3'
#  {{.CLI_ARGS}} can be applied via -- <pytest-args>
# for debugging one can add a databaseFile then it will use a file instead of the :memory:
# common pytest arg is -k to reduce the test that will be run
tasks:
    default:
        deps: [run]
    run:
        desc: run authservice with local config
        cmds:
            - poetry run python auth_service/main.py -c ./config.yml {{.CLI_ARGS}}
    test:
        desc: run tests
        cmds:
            - poetry run python -m pytest tests/ {{.CLI_ARGS}}
    build: 
        desc: Build package
        cmds: 
            - poetry build
    clean-build:
        desc: clean dist folder
        cmds:
            - rm -rf dist/
